name: Build

on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout theos/sdks
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          ref: master
          sparse-checkout: iPhoneOS16.5.sdk
          path: theos/sdks

      - name: Ensure main utils are installed
        uses: dhinakg/procursus-action@main
        with:
          packages: coreutils make xz ldid

      - name: Create Download Header file.
        run: |
          echo "#define GEODE_DOWNLOAD_URL @\"${{ secrets.DOWNLOAD_LINK }}\"" > geode_download.h
          
      - name: Build
        run: |
          export THEOS=theos

          git submodule init
          git submodule update
          gmake package FINALPACKAGE=1 STRIP=0
          gmake package FINALPACKAGE=1 STRIP=0 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: packages
          path: packages/*.deb
